return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    main = "nvim-treesitter.configs",
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "cpp",
            "css",
            "diff",
            "go",
            "html",
            "javascript",
            "json",
            "json5",
            "lua",
            "luadoc",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "ruby",
            "rust",
            "scss",
            "toml",
            "typescript",
            "vim",
            "vimdoc",
            "yaml",
        },
        auto_install = true,
        highlight = {
            enable = true,
            disable = { "latex" },
        },
        indent = { enable = true },
    },
}
