return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    branch = "main",
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "cpp",
            "css",
            "diff",
            "go",
            "html",
            "javascript",
            "json",
            "json5",
            "latex",
            "lua",
            "luadoc",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "ruby",
            "rust",
            "scss",
            "toml",
            "tsx",
            "typescript",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
        },
        auto_install = true,
        highlight = {
            enable = true,
        },
        indent = { enable = true },
    },
    config = function(_, opts)
        require("nvim-treesitter.configs").setup(opts)
    end,
}
